# format = '$all'
add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

# Which is equivalent to
# $gcloud\
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$package\
$cmake\
$daml\
$deno\
$dotnet\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$tofu\
$typst\
$vlang\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$aws\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$line_break\
$jobs\
$status\
$os\
$container\
$shell\
$character"""

right_format = """
$cmd_duration"""

[fill]
symbol = ' '
